language: python
python:
- '3.4'
- '2.7'
- '2.6'
install:
- pip install -r requirements.txt --use-mirrors
- pip install -r test-requirements.txt --use-mirrors
- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2;
script: nosetests
deploy:
  provider: pypi
  user: William.Pain
  password:
    secure: eYnUDGDgrrrTEBPb9I5nJ3DMKNCC7EkCroBAZRCRrYytVi+jzZcqrsj7YxEmNJUyRRXgYUMJU+4WtnDlV0/ti92BO3S/R17VF8uvn1wxNRVI0UiBIEgmhCZX634eYYFVD8jqXgfhiQnLQkwoG/SkqzEytdlVLEj4RWUfZvKOcGQ=
  on:
    tags: true
    repo: checkmyws/checkmyws-python
