language: python
python:
- '3.3'
- '2.7'
install:
- pip install -r requirements.txt --use-mirrors
- pip install -r test-requirements.txt --use-mirrors
script: nosetests
deploy:
  provider: pypi
  user: William.Pain
  password:
    secure: PP9wdtx88d896AGMzqzx0vQoSU6gFU1I63HDDIYtuCxZbLPoqIEkuLpfnySC5OcC6sArIU3B0EvjsH9FuVuN0HVxEFmcbEvEok6RJLahFzTwKZ1jg9TdXFuqrzefjaNwrmOPZdEMs7JDliarI8ZvevomV9QgWce7rgkiV6yGWD8=
  on:
    tags: true
    repo: checkmyws/checkmyws-python
